name: Convert Notebooks to HTML

on:
  push:
    branches:
      - main  # or master, depending on your default branch
    paths:
      - 'notebooks/**'  # Only run when notebooks are updated

jobs:
  convert-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          
      - name: Convert Jupyter notebooks to HTML
        run: |
          mkdir -p html_notebooks
          cd notebooks
          for notebook in *.ipynb; do
            echo "Converting $notebook to HTML..."
            jupyter nbconvert --to html --output-dir=../html_notebooks "$notebook"
          done
          
      - name: Deploy HTML notebooks
        run: |
          cp -r html_notebooks/* .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.html
          git commit -m "Convert notebooks to HTML" || echo "No changes to commit"
          git push 